#!/bin/bash

# ====== 1. Создаём .gitignore для Unity ======
cat > .gitignore <<EOL
# Unity autogenerated folders
Library/
Temp/
Obj/
Build/
Logs/
MemoryCaptures/

# OS generated files
.DS_Store
Thumbs.db

# Visual Studio / Rider
.vscode/
*.csproj
*.sln
*.user
*.pidb
*.suo
*.unityproj
*.booproj
EOL

echo ".gitignore создан."

# ====== 2. Инициализация Git ======
git init
echo "Git репозиторий инициализирован."

# ====== 3. Добавляем файлы и делаем коммит ======
git add .
git commit -m "Initial commit: clean Unity project with .gitignore"
echo "Первый коммит создан."
remoteURL="<YOUR_GITHUB_URL>"remoteURL="https://github.com/dobrichloly/Azur-games-test-project.git"

# ====== 4. Подключаем удалённый репозиторий ======
remoteURL="<YOUR_GITHUB_URL>"  # <-- Вставь сюда URL твоего репозитория
git remote add origin $remoteURL
echo "Удалённый репозиторий подключен: $remoteURL"

# ====== 5. Пушим на GitHub ======
git branch -M main
git push -u origin main
echo "Push выполнен. Проект теперь на GitHub!"
